# Variant characters (outside the 8105 standard) -> the standard character, from Unihan.
import re, os, sys
R = sys.argv[1]
std = set(open("/tmp/std8105.txt", encoding="utf-8").read().strip())
ts = open(os.path.join(R, "lib/text/simplified.ts"), encoding="utf-8").read()
F = re.search(r'const FROM =\s*"([^"]+)"', ts).group(1); T = re.search(r'const TO =\s*"([^"]+)"', ts).group(1)
t2s = dict(zip(list(F), list(T)))
var = {}
def ch(u): return chr(int(u[2:], 16))
for line in open("/tmp/unihan/Unihan_Variants.txt", encoding="utf-8"):
    if line.startswith("#") or not line.strip(): continue
    cp, field, val = line.rstrip("\n").split("\t")
    if field not in ("kSemanticVariant", "kZVariant", "kSpecializedSemanticVariant", "kSimplifiedVariant", "kTraditionalVariant"): continue
    c = ch(cp)
    for tok in val.split():
        v = ch(tok.split("<")[0])
        var.setdefault(c, []).append((field, v))
order = {"kSimplifiedVariant": 0, "kZVariant": 1, "kSemanticVariant": 2, "kSpecializedSemanticVariant": 3, "kTraditionalVariant": 4}
def to_std(c, depth=0):
    if c in std: return c
    s = t2s.get(c)
    if s and s in std: return s
    if depth > 1: return None
    for field, v in sorted(var.get(c, []), key=lambda x: order[x[0]]):
        r = to_std(v, depth + 1)
        if r: return r
    return None
out = {}
for c in var:
    if c in std or c in t2s: continue   # standard chars, and Traditional ones toSimplified already handles
    cp = ord(c)
    if not (0x3400 <= cp <= 0x9FFF): continue
    r = to_std(c)
    if r and r != c: out[c] = r
for c, want in {"愬": "诉", "槀": "稿", "坿": "附", "寔": "实", "峕": "时", "藁": "稿", "攷": "考", "艸": "草", "妳": "你"}.items():
    print(c, "->", out.get(c), "want", want)
print("entries", len(out))
keys = "".join(out.keys()); vals = "".join(out[k] for k in out)
open(os.path.join(R, "lib/text/variants.ts"), "w", encoding="utf-8").write(f'''/**
 * Variant characters outside 《通用规范汉字表》 and the standard one each stands
 * for, from Unicode's Unihan variant data (kSimplifiedVariant, kZVariant,
 * kSemanticVariant). A browser converter on the client's machine rewrites the
 * page into such variants (告愬 for 告诉, 槀子 for 稿子, 坿 for 附, 4 Oct);
 * SimplifiedGuard turns them back. Generated by scripts/gen-variants.py.
 */
const FROM = "{keys}";
const TO = "{vals}";
const MAP = new Map<string, string>();
{{
  const f = Array.from(FROM);
  const t = Array.from(TO);
  for (let i = 0; i < f.length; i++) MAP.set(f[i], t[i]);
}}

/** The text with every known variant character replaced by the standard one. */
export function fixVariantChars(text: string): string {{
  let out = "";
  for (const c of text) out += MAP.get(c) ?? c;
  return out;
}}

export function hasVariantChars(text: string): boolean {{
  for (const c of text) if (MAP.has(c)) return true;
  return false;
}}

export const VARIANT_COUNT = {len(out)};
''')
