# Builds lib/text/simplified.ts from OpenCC's t2s dictionaries.
#   /tmp/occ/bin/python3 gen_simplified.py
import os, json

DICT = "/tmp/occ/lib/python3.12/site-packages/opencc/dictionary"
OUT = "/home/ubuntu/projects/aiVideoFreeLance/lib/text/simplified.ts"


def load(name, keep_identity):
    pairs = {}
    for line in open(os.path.join(DICT, name), encoding="utf-8"):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        src, dst = parts[0], parts[1].split(" ")[0]
        if src != dst or keep_identity:
            pairs[src] = dst
    return pairs


chars = load("TSCharacters.txt", keep_identity=False)

# Some of OpenCC's Simplified forms live above U+FFFF, and neither the webfont
# the site ships nor the Noto Sans CJK SC that ffmpeg burns subtitles with has
# a glyph for any of them. Converting would turn readable text into empty
# boxes, which is the very complaint this work started from. The one that
# actually occurs in this studio's Cantonese is 嗰 -> 𠮶 (U+20BB6); the other
# six hundred are characters nobody has typed since the Qing. The Traditional
# form stays, because a character that can be read beats one that cannot.
outside_bmp = [k for k, v in chars.items() if any(ord(c) > 0xFFFF for c in v)]
for k in outside_bmp:
    del chars[k]
# Identity phrases matter: `乾元 -> 乾元` exists only to stop the character rule
# `乾 -> 干` from firing inside it.
phrases = load("TSPhrases.txt", keep_identity=True)

for k in [k for k, v in phrases.items() if any(ord(c) > 0xFFFF for c in v)]:
    del phrases[k]

redundant = [k for k, v in phrases.items() if "".join(chars.get(c, c) for c in k) == v]
for k in redundant:
    del phrases[k]

src_chars = "".join(chars.keys())
dst_chars = "".join(chars.values())

HEADER = '''/**
 * Traditional Chinese in, Simplified Chinese out.
 *
 * The studio publishes in Simplified only, but two of its sources do not know
 * that: Whisper writes Cantonese, and a good deal of Mandarin, in Traditional,
 * and a model asked for Chinese answers in whichever form its training leaned.
 * Both land in the database, so the conversion belongs at the seam where text
 * arrives rather than in a component, where it would be redone on every render
 * and missed by anything that reads the row directly.
 *
 * The tables are OpenCC's `t2s`. The %d phrases are the runs where converting
 * character by character would be wrong — including the ones that map to
 * themselves, which exist only to stop a character rule firing inside them.
 * Generated by scripts/gen-simplified.py; edit that, not this.
 */

/* %d characters, as two aligned lists: cheaper to ship and to parse than an
   object with that many keys. */
const FROM =
  %s;
const TO =
  %s;

const PHRASES: [string, string][] = %s;

/* Both tables are walked by code point, not by UTF-16 unit: a handful of the
   Traditional characters and more of their Simplified forms live above U+FFFF,
   and indexing those by `.length` silently shifts every pair after them. */
const TABLE = new Map<string, string>();
{
  const from = Array.from(FROM);
  const to = Array.from(TO);
  if (from.length !== to.length) throw new Error("simplified.ts: the tables are not aligned");
  for (let i = 0; i < from.length; i++) TABLE.set(from[i], to[i]);
}

const PHRASE_MAP = new Map<string, string>(PHRASES);

const LONGEST = PHRASES.reduce((n, [k]) => Math.max(n, Array.from(k).length), 0);

/** True when the text holds at least one character Simplified spells
 *  differently. Cheap enough to run on a row before deciding to write it. */
export function hasTraditional(text: string): boolean {
  for (const ch of text) if (TABLE.has(ch)) return true;
  return false;
}

/**
 * Convert a string to Simplified Chinese. Anything that is not Traditional —
 * English, punctuation, emoji, Simplified already — comes back untouched, so
 * this is safe over mixed text and over text that has been through it before.
 */
export function toSimplified(text: string): string {
  if (!text) return text;
  const chars = Array.from(text);
  let out = "";
  for (let i = 0; i < chars.length; ) {
    let matched = false;
    for (let n = Math.min(LONGEST, chars.length - i); n > 1 && !matched; n--) {
      const hit = PHRASE_MAP.get(chars.slice(i, i + n).join(""));
      if (hit !== undefined) {
        out += hit;
        i += n;
        matched = true;
      }
    }
    if (matched) continue;
    out += TABLE.get(chars[i]) ?? chars[i];
    i += 1;
  }
  return out;
}
'''

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(HEADER % (
        len(phrases),
        len(chars),
        json.dumps(src_chars, ensure_ascii=False),
        json.dumps(dst_chars, ensure_ascii=False),
        json.dumps(sorted(phrases.items(), key=lambda kv: (-len(kv[0]), kv[0])), ensure_ascii=False),
    ))

print("chars", len(chars), "phrases", len(phrases), "dropped (non-BMP)", len(outside_bmp), "bytes", os.path.getsize(OUT))
