import "server-only";
import { and, eq } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { files } from "@/lib/db/schema";
import type { Viewer } from "@/lib/auth/types";
import { env } from "@/lib/env";
import "@/lib/keys/boot";
import { beginUpload, completeUpload, importVideoBytes } from "@/lib/files/service";
import { getObject, presignDownload, putObjectConfirmed } from "@/lib/storage/r2";
import { narrate } from "@/lib/video/tts";
import { LOCAL_VOICES, voiceLanguage } from "@/lib/video/tts/voices";
import { relayHeaders, voices as elevenVoices } from "@/lib/video/elevenlabs";

/**
 * 配音和生成 (7 Oct: "a UI for voice generation and video generation, with
 * voice cloning"). Voice-over is read by the server's own engine for its
 * voices and by ElevenLabs for library and cloned voices; cloning is
 * ElevenLabs' instant voice clone; video is generated through fal.ai, one key
 * for Kling, Hailuo and Seedance. Everything made lands in Files.
 */

export type StudioVoice = { id: string; name: string; lang: "zh" | "en" | null; gender: string | null; source: "local" | "elevenlabs" };

/** Put generated bytes into this person's Files (their home folder unless one is named). */
export async function storeBytes(viewer: Viewer, input: { bytes: Uint8Array; name: string; mime: string; folderId?: string | null }) {
  const { file, storageKey } = await beginUpload(viewer, { name: input.name, mime: input.mime, sizeBytes: input.bytes.byteLength, folderId: input.folderId ?? null });
  const stored = await putObjectConfirmed(storageKey, new Uint8Array(input.bytes) as Uint8Array<ArrayBuffer>, input.mime);
  await completeUpload(viewer, file.id, stored.etag ?? undefined);
  return { id: file.id, name: input.name };
}

/** Whether ElevenLabs answers from this server: set up, and not refusing the address. */
export async function elevenStatus(): Promise<"ok" | "no-key" | "refused" | "error"> {
  if (!env.elevenlabs.apiKey) return "no-key";
  try {
    await elevenVoices();
    return "ok";
  } catch (err) {
    const status = (err as { status?: number }).status;
    return status === 403 || /redirected/i.test(String((err as Error).message)) ? "refused" : "error";
  }
}

export async function studioVoices(): Promise<{ voices: StudioVoice[]; eleven: Awaited<ReturnType<typeof elevenStatus>> }> {
  const local: StudioVoice[] = LOCAL_VOICES.map((v) => ({ id: v.id, name: v.name.zh, lang: v.lang, gender: v.gender, source: "local" }));
  const eleven = await elevenStatus();
  let remote: StudioVoice[] = [];
  if (eleven === "ok") {
    /* The host's own clones first (Avon, 10 Oct), then the studio's other clones, then ElevenLabs' stock library. */
    const rank = (v: { name: string; category: string | null }) => (/avon|亚芳/i.test(v.name) ? 0 : v.category === "cloned" || v.category === "professional" ? 1 : v.category === "generated" ? 2 : 3);
    remote = (await elevenVoices().catch(() => []))
      .sort((a, b) => rank(a) - rank(b) || a.name.localeCompare(b.name))
      .map((v) => ({ id: `elevenlabs:${v.id}`, name: rank(v) <= 1 ? `${v.name}（克隆）` : v.name, lang: null, gender: null, source: "elevenlabs" as const }));
  }
  return { voices: [...remote, ...local], eleven };
}

/** Read text aloud and keep it in Files as an MP3. */
export async function speakToFile(viewer: Viewer, input: { text: string; voiceId: string }) {
  const n = await narrate({ text: input.text, voiceId: input.voiceId });
  const head = input.text.replace(/\s+/g, " ").trim().slice(0, 18);
  const made = await storeBytes(viewer, { bytes: new Uint8Array(n.mp3), name: `配音 · ${head || "未命名"}.mp3`, mime: "audio/mpeg" });
  return { ...made, durationMs: n.durationMs, lang: voiceLanguage(input.voiceId) };
}

/** ElevenLabs instant voice clone from audio files the person can read (their own uploads). */
export async function cloneVoice(viewer: Viewer, input: { name: string; fileIds: string[]; description?: string }) {
  if (!env.elevenlabs.apiKey) throw new Error("还没有设置 ElevenLabs 密钥（员工管理 › 渠道与凭据）");
  const form = new FormData();
  form.set("name", input.name.slice(0, 60));
  if (input.description) form.set("description", input.description.slice(0, 300));
  let n = 0;
  for (const id of input.fileIds.slice(0, 5)) {
    const [f] = await db.select({ name: files.name, key: files.storageKey, mime: files.mime }).from(files).where(and(eq(files.id, id), eq(files.tenantId, viewer.tenantId))).limit(1);
    if (!f?.key) continue;
    const res = await getObject(f.key);
    if (!res.ok) continue;
    form.append("files", new Blob([await res.arrayBuffer()], { type: f.mime ?? "audio/mpeg" }), f.name);
    n++;
  }
  if (!n) throw new Error("没找到可用的声音样本，请上传一段 1 分钟以上的清晰录音（mp3、wav 或 m4a）");
  const res = await fetch(`${env.elevenlabs.baseUrl}/voices/add`, { method: "POST", headers: { "xi-api-key": env.elevenlabs.apiKey, ...relayHeaders() }, body: form, signal: AbortSignal.timeout(180_000) });
  if (new URL(res.url).origin !== new URL(env.elevenlabs.baseUrl).origin) throw new Error("ElevenLabs 拒绝了服务器所在的网络，需要先接通（见页面上的说明）");
  const text = await res.text();
  if (!res.ok) {
    let detail = text.slice(0, 200);
    try {
      const d = JSON.parse(text) as { detail?: { message?: string } | string };
      detail = typeof d.detail === "string" ? d.detail : (d.detail?.message ?? detail);
    } catch {
      /* the raw words */
    }
    throw new Error(res.status === 401 ? "ElevenLabs 不认这个密钥" : /subscription|plan|tier/i.test(detail) ? `ElevenLabs 套餐不支持克隆声音（免费版不能克隆，需要 Starter 及以上）：${detail}` : `ElevenLabs：${detail}`);
  }
  const voiceId = (JSON.parse(text) as { voice_id?: string }).voice_id;
  if (!voiceId) throw new Error("ElevenLabs 没有返回新声音");
  return { voiceId: `elevenlabs:${voiceId}` };
}

/* ------------------------------------------------------------ video generation */

export const VIDEO_MODELS: { id: string; zh: string; en: string; noteZh: string; image: string | null }[] = [
  { id: "fal-ai/kling-video/v2.1/standard/text-to-video", zh: "可灵 Kling", en: "Kling", noteZh: "画面稳定、人物自然，5 或 10 秒", image: "fal-ai/kling-video/v2.1/standard/image-to-video" },
  { id: "fal-ai/minimax/hailuo-02/standard/text-to-video", zh: "海螺 Hailuo", en: "Hailuo", noteZh: "动作和镜头感强，6 或 10 秒", image: "fal-ai/minimax/hailuo-02/standard/image-to-video" },
  { id: "fal-ai/bytedance/seedance/v1/lite/text-to-video", zh: "即梦 Seedance", en: "Seedance", noteZh: "便宜、出片快", image: "fal-ai/bytedance/seedance/v1/lite/image-to-video" },
];

type FalQueued = { request_id?: string; status_url?: string; response_url?: string; detail?: unknown };

const falHeaders = () => {
  const key = process.env.FAL_KEY;
  if (!key) throw new Error("还没有设置 fal.ai 密钥（员工管理 › 渠道与凭据）");
  return { authorization: `Key ${key}`, "content-type": "application/json" };
};

/** On the worker (`media.generateVideo`): ask fal.ai, wait for the video, keep it in Files. */
export async function generateVideo(
  viewer: Viewer,
  input: { prompt: string; model: string; aspect: "16:9" | "9:16" | "1:1"; seconds: number; imageFileId?: string | null },
  onProgress: (f: number) => void = () => {},
) {
  const spec = VIDEO_MODELS.find((m) => m.id === input.model) ?? VIDEO_MODELS[0];
  let model = spec.id;
  const body: Record<string, unknown> = { prompt: input.prompt.slice(0, 2000), aspect_ratio: input.aspect, duration: String(input.seconds) };
  if (input.imageFileId && spec.image) {
    const [f] = await db.select({ key: files.storageKey }).from(files).where(and(eq(files.id, input.imageFileId), eq(files.tenantId, viewer.tenantId))).limit(1);
    if (f?.key) {
      body.image_url = await presignDownload(f.key, { expiresIn: 3600 });
      model = spec.image;
    }
  }
  const url = await runFal(model, body, onProgress, "换个描述再试一次");
  onProgress(0.9);
  const bytes = new Uint8Array(await (await fetch(url, { signal: AbortSignal.timeout(300_000) })).arrayBuffer());
  const made = await importVideoBytes(viewer, {
    bytes,
    name: `AI 生成 · ${input.prompt.replace(/\s+/g, " ").slice(0, 30)}`,
    attribution: `AI 生成（${spec.zh}）`,
    source: input.prompt.slice(0, 500),
    meta: { source: "ai-video", model, prompt: input.prompt.slice(0, 1000), kind: "video", fetchedAt: new Date().toISOString() } as never,
    tags: ["ai-generated"],
  });
  onProgress(1);
  return { fileId: made.id, name: made.name, durationMs: made.durationMs, model };
}

/** One fal.ai queue request, waited for: the URL of the video it made. */
async function runFal(model: string, body: Record<string, unknown>, onProgress: (f: number) => void, retryHint: string): Promise<string> {
  const q = await fetch(`https://queue.fal.run/${model}`, { method: "POST", headers: falHeaders(), body: JSON.stringify(body), signal: AbortSignal.timeout(60_000) });
  const queued = (await q.json().catch(() => ({}))) as FalQueued;
  if (!q.ok || !queued.status_url || !queued.response_url) {
    throw new Error(q.status === 401 || q.status === 403 ? "fal.ai 不认这个密钥" : q.status === 402 ? "fal.ai 余额不足，请先充值" : `fal.ai 没接这个任务：${JSON.stringify(queued.detail ?? queued).slice(0, 200)}`);
  }
  const started = Date.now();
  for (;;) {
    await new Promise((r) => setTimeout(r, 5000));
    const s = (await (await fetch(queued.status_url, { headers: falHeaders() })).json().catch(() => ({}))) as { status?: string };
    const elapsed = Date.now() - started;
    onProgress(Math.min(0.85, elapsed / 240_000));
    if (s.status === "COMPLETED") break;
    if (s.status === "FAILED" || s.status === "ERROR") throw new Error(`fal.ai 生成失败，${retryHint}`);
    if (elapsed > 20 * 60_000) throw new Error("生成超过 20 分钟还没好，已放弃，请再试一次");
  }
  const out = (await (await fetch(queued.response_url, { headers: falHeaders() })).json().catch(() => ({}))) as { video?: { url?: string }; detail?: unknown };
  const url = out.video?.url;
  if (!url) throw new Error(`fal.ai 没有返回视频：${JSON.stringify(out.detail ?? out).slice(0, 160)}`);
  return url;
}

/* ------------------------------------------------------------ lip-sync on this machine */

/**
 * Wav2Lip on the server's own CPU (10 Oct): free, her real footage, the
 * mouth re-timed to the new audio. About seven times real time at 480p, so
 * a minute of video is seven minutes of waiting; the worker runs it at low
 * priority so the site stays quick. Installed under ~/lipsync (setup.sh).
 */
async function localLipSync(hostKey: string, audioKey: string, onProgress: (f: number) => void): Promise<Uint8Array> {
  const { execFile } = await import("node:child_process");
  const { mkdtemp, readFile, rm, writeFile, stat } = await import("node:fs/promises");
  const path = await import("node:path");
  const os = await import("node:os");
  const home = process.env.HOME || os.homedir();
  const runner = path.join(home, "lipsync", "run.sh");
  if (!(await stat(runner).catch(() => null))) throw new Error("这台服务器还没装本机对口型（lipsync/run.sh）");
  const dir = await mkdtemp(path.join(os.tmpdir(), "tg-lip-"));
  try {
    const [face, audio] = await Promise.all([getObject(hostKey), getObject(audioKey)]);
    if (!face.ok || !audio.ok) throw new Error("主持人素材或声音读不出来");
    const facePath = path.join(dir, "face.bin");
    const audioPath = path.join(dir, "audio.bin");
    const outPath = path.join(dir, "out.mp4");
    await writeFile(facePath, new Uint8Array(await face.arrayBuffer()));
    await writeFile(audioPath, new Uint8Array(await audio.arrayBuffer()));
    onProgress(0.05);
    /* The runner says nothing useful while it works, so progress is time against a seven-to-one estimate. */
    const seconds = await new Promise<number>((resolve) => execFile("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", audioPath], (e, out) => resolve(e ? 30 : Number(out) || 30)));
    const started = Date.now();
    const tick = setInterval(() => onProgress(Math.min(0.95, 0.05 + ((Date.now() - started) / 1000 / (seconds * 7.5)) * 0.9)), 5000);
    try {
      await new Promise<void>((resolve, reject) => {
        execFile("bash", [runner, facePath, audioPath, outPath], { timeout: 40 * 60_000, maxBuffer: 16 * 1024 * 1024 }, (err, _stdout, stderr) => {
          if (err) reject(new Error(`对口型没成功：${String(stderr).split("\n").filter(Boolean).slice(-2).join(" ").slice(0, 200) || err.message}`));
          else resolve();
        });
      });
    } finally {
      clearInterval(tick);
    }
    return new Uint8Array(await readFile(outPath));
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

/* ------------------------------------------------------------ the host, talking */

/**
 * 主持人口播 (Ryan, 5 Oct: "they just want their host talking … clone the
 * host and get her talk"). A photo or a short clip of the host, and the
 * words: read in her cloned voice (or any voice), then her face is made to
 * say them. A photo goes to an avatar model that animates the whole head; a
 * clip keeps her real footage and only re-times the mouth.
 */
export const HOST_ENGINES: { id: string; for: "image" | "video"; zh: string; en: string; noteZh: string }[] = [
  { id: "local/wav2lip", for: "video", zh: "本机对口型（免费）", en: "Lip-sync on our server (free)", noteZh: "不花钱，用她的真实视频，嘴型清晰度一般；一分钟约等 7 分钟" },
  { id: "fal-ai/kling-video/ai-avatar/v2/standard", for: "image", zh: "可灵数字人（照片）", en: "Kling avatar (photo)", noteZh: "一张正脸照片就能说话，表情自然" },
  { id: "veed/fabric-1.0", for: "image", zh: "Fabric（照片，便宜）", en: "Fabric (photo, cheaper)", noteZh: "720p，比可灵贵一些" },
  { id: "fal-ai/sync-lipsync/v2", for: "video", zh: "对口型（视频）", en: "Lip-sync (clip)", noteZh: "用她真实的视频，只改嘴型，最像本人" },
];

export async function talkingHost(
  viewer: Viewer,
  input: { hostFileId: string; text?: string | null; audioFileId?: string | null; voiceId?: string | null; engine?: string | null },
  onProgress: (f: number) => void = () => {},
) {
  const [host] = await db.select({ key: files.storageKey, mime: files.mime, name: files.name }).from(files).where(and(eq(files.id, input.hostFileId), eq(files.tenantId, viewer.tenantId))).limit(1);
  if (!host?.key) throw new Error("找不到主持人的照片或视频");
  const isVideo = (host.mime ?? "").startsWith("video/") || /\.(mp4|mov|m4v|webm)$/i.test(host.name);
  const isImage = (host.mime ?? "").startsWith("image/") || /\.(jpe?g|png|webp)$/i.test(host.name);
  if (!isVideo && !isImage) throw new Error("主持人素材要是一张照片（jpg、png）或一段视频（mp4、mov）");
  const engine = HOST_ENGINES.find((e) => e.id === input.engine && e.for === (isVideo ? "video" : "image")) ?? HOST_ENGINES.find((e) => e.for === (isVideo ? "video" : "image"))!;

  /* The words as audio: an audio file given, or read now and kept in Files. */
  let audioKey: string | null = null;
  let audioId: string | null = null;
  if (input.audioFileId) {
    const [a] = await db.select({ key: files.storageKey }).from(files).where(and(eq(files.id, input.audioFileId), eq(files.tenantId, viewer.tenantId))).limit(1);
    audioKey = a?.key ?? null;
    audioId = input.audioFileId;
  } else if (input.text?.trim() && input.voiceId) {
    onProgress(0.03);
    const spoken = await speakToFile(viewer, { text: input.text.trim(), voiceId: input.voiceId });
    audioId = spoken.id;
    const [a] = await db.select({ key: files.storageKey }).from(files).where(eq(files.id, spoken.id)).limit(1);
    audioKey = a?.key ?? null;
  }
  if (!audioKey) throw new Error("没有可用的声音：写下要说的话并选一个声音，或者选一段录音");
  onProgress(0.1);

  const hostUrl = await presignDownload(host.key, { expiresIn: 3 * 3600 });
  const audioUrl = await presignDownload(audioKey, { expiresIn: 3 * 3600 });
  const body: Record<string, unknown> =
    engine.id === "fal-ai/sync-lipsync/v2"
      ? { video_url: hostUrl, audio_url: audioUrl, sync_mode: "bounce" }
      : engine.id === "veed/fabric-1.0"
        ? { image_url: hostUrl, audio_url: audioUrl, resolution: "720p" }
        : { image_url: hostUrl, audio_url: audioUrl, prompt: "一位主持人面对镜头自然地讲话，表情生动，头部有轻微自然的动作。" };
  let bytes: Uint8Array;
  if (engine.id === "local/wav2lip") {
    bytes = await localLipSync(host.key, audioKey, (f) => onProgress(0.1 + f * 0.82));
  } else {
    const url = await runFal(engine.id, body, (f) => onProgress(0.1 + f * 0.8), "换一张更清晰的正脸素材再试一次");
    onProgress(0.92);
    bytes = new Uint8Array(await (await fetch(url, { signal: AbortSignal.timeout(300_000) })).arrayBuffer());
  }
  const head = (input.text ?? "").replace(/\s+/g, " ").trim().slice(0, 24) || "口播";
  const made = await importVideoBytes(viewer, {
    bytes,
    name: `主持人口播 · ${head}`,
    attribution: `AI 生成（${engine.zh}）`,
    source: (input.text ?? "").slice(0, 500),
    meta: { source: "ai-host", model: engine.id, hostFileId: input.hostFileId, audioFileId: audioId, kind: "video", fetchedAt: new Date().toISOString() } as never,
    tags: ["ai-generated", "host"],
  });
  onProgress(1);
  return { fileId: made.id, name: made.name, durationMs: made.durationMs, model: engine.id, audioFileId: audioId };
}
