import "server-only";
import { and, eq } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { files } from "@/lib/db/schema";
import type { Viewer } from "@/lib/auth/types";
import { env } from "@/lib/env";
import "@/lib/keys/boot";
import { beginUpload, completeUpload, importVideoBytes } from "@/lib/files/service";
import { getObject, presignDownload, putObjectConfirmed } from "@/lib/storage/r2";
import { narrate } from "@/lib/video/tts";
import { LOCAL_VOICES, voiceLanguage } from "@/lib/video/tts/voices";
import { voices as elevenVoices } from "@/lib/video/elevenlabs";

/**
 * 配音和生成 (7 Oct: "a UI for voice generation and video generation, with
 * voice cloning"). Voice-over is read by the server's own engine for its
 * voices and by ElevenLabs for library and cloned voices; cloning is
 * ElevenLabs' instant voice clone; video is generated through fal.ai, one key
 * for Kling, Hailuo and Seedance. Everything made lands in Files.
 */

export type StudioVoice = { id: string; name: string; lang: "zh" | "en" | null; gender: string | null; source: "local" | "elevenlabs" };

/** Put generated bytes into this person's Files (their home folder unless one is named). */
export async function storeBytes(viewer: Viewer, input: { bytes: Uint8Array; name: string; mime: string; folderId?: string | null }) {
  const { file, storageKey } = await beginUpload(viewer, { name: input.name, mime: input.mime, sizeBytes: input.bytes.byteLength, folderId: input.folderId ?? null });
  const stored = await putObjectConfirmed(storageKey, new Uint8Array(input.bytes) as Uint8Array<ArrayBuffer>, input.mime);
  await completeUpload(viewer, file.id, stored.etag ?? undefined);
  return { id: file.id, name: input.name };
}

/** Whether ElevenLabs answers from this server: set up, and not refusing the address. */
export async function elevenStatus(): Promise<"ok" | "no-key" | "refused" | "error"> {
  if (!env.elevenlabs.apiKey) return "no-key";
  try {
    await elevenVoices();
    return "ok";
  } catch (err) {
    const status = (err as { status?: number }).status;
    return status === 403 || /redirected/i.test(String((err as Error).message)) ? "refused" : "error";
  }
}

export async function studioVoices(): Promise<{ voices: StudioVoice[]; eleven: Awaited<ReturnType<typeof elevenStatus>> }> {
  const local: StudioVoice[] = LOCAL_VOICES.map((v) => ({ id: v.id, name: v.name.zh, lang: v.lang, gender: v.gender, source: "local" }));
  const eleven = await elevenStatus();
  let remote: StudioVoice[] = [];
  if (eleven === "ok") {
    remote = (await elevenVoices().catch(() => [])).map((v) => ({ id: `elevenlabs:${v.id}`, name: v.name, lang: null, gender: null, source: "elevenlabs" as const }));
  }
  return { voices: [...remote, ...local], eleven };
}

/** Read text aloud and keep it in Files as an MP3. */
export async function speakToFile(viewer: Viewer, input: { text: string; voiceId: string }) {
  const n = await narrate({ text: input.text, voiceId: input.voiceId });
  const head = input.text.replace(/\s+/g, " ").trim().slice(0, 18);
  const made = await storeBytes(viewer, { bytes: new Uint8Array(n.mp3), name: `配音 · ${head || "未命名"}.mp3`, mime: "audio/mpeg" });
  return { ...made, durationMs: n.durationMs, lang: voiceLanguage(input.voiceId) };
}

/** ElevenLabs instant voice clone from audio files the person can read (their own uploads). */
export async function cloneVoice(viewer: Viewer, input: { name: string; fileIds: string[]; description?: string }) {
  if (!env.elevenlabs.apiKey) throw new Error("还没有设置 ElevenLabs 密钥（员工管理 › 渠道与凭据）");
  const form = new FormData();
  form.set("name", input.name.slice(0, 60));
  if (input.description) form.set("description", input.description.slice(0, 300));
  let n = 0;
  for (const id of input.fileIds.slice(0, 5)) {
    const [f] = await db.select({ name: files.name, key: files.storageKey, mime: files.mime }).from(files).where(and(eq(files.id, id), eq(files.tenantId, viewer.tenantId))).limit(1);
    if (!f?.key) continue;
    const res = await getObject(f.key);
    if (!res.ok) continue;
    form.append("files", new Blob([await res.arrayBuffer()], { type: f.mime ?? "audio/mpeg" }), f.name);
    n++;
  }
  if (!n) throw new Error("没找到可用的声音样本，请上传一段 1 分钟以上的清晰录音（mp3、wav 或 m4a）");
  const res = await fetch(`${env.elevenlabs.baseUrl}/v1/voices/add`, { method: "POST", headers: { "xi-api-key": env.elevenlabs.apiKey }, body: form, signal: AbortSignal.timeout(180_000) });
  if (new URL(res.url).origin !== new URL(env.elevenlabs.baseUrl).origin) throw new Error("ElevenLabs 拒绝了服务器所在的网络，需要先接通（见页面上的说明）");
  const text = await res.text();
  if (!res.ok) {
    let detail = text.slice(0, 200);
    try {
      const d = JSON.parse(text) as { detail?: { message?: string } | string };
      detail = typeof d.detail === "string" ? d.detail : (d.detail?.message ?? detail);
    } catch {
      /* the raw words */
    }
    throw new Error(res.status === 401 ? "ElevenLabs 不认这个密钥" : /subscription|plan|tier/i.test(detail) ? `ElevenLabs 套餐不支持克隆声音（免费版不能克隆，需要 Starter 及以上）：${detail}` : `ElevenLabs：${detail}`);
  }
  const voiceId = (JSON.parse(text) as { voice_id?: string }).voice_id;
  if (!voiceId) throw new Error("ElevenLabs 没有返回新声音");
  return { voiceId: `elevenlabs:${voiceId}` };
}

/* ------------------------------------------------------------ video generation */

export const VIDEO_MODELS: { id: string; zh: string; en: string; noteZh: string; image: string | null }[] = [
  { id: "fal-ai/kling-video/v2.1/standard/text-to-video", zh: "可灵 Kling", en: "Kling", noteZh: "画面稳定、人物自然，5 或 10 秒", image: "fal-ai/kling-video/v2.1/standard/image-to-video" },
  { id: "fal-ai/minimax/hailuo-02/standard/text-to-video", zh: "海螺 Hailuo", en: "Hailuo", noteZh: "动作和镜头感强，6 或 10 秒", image: "fal-ai/minimax/hailuo-02/standard/image-to-video" },
  { id: "fal-ai/bytedance/seedance/v1/lite/text-to-video", zh: "即梦 Seedance", en: "Seedance", noteZh: "便宜、出片快", image: "fal-ai/bytedance/seedance/v1/lite/image-to-video" },
];

type FalQueued = { request_id?: string; status_url?: string; response_url?: string; detail?: unknown };

const falHeaders = () => {
  const key = process.env.FAL_KEY;
  if (!key) throw new Error("还没有设置 fal.ai 密钥（员工管理 › 渠道与凭据）");
  return { authorization: `Key ${key}`, "content-type": "application/json" };
};

/** On the worker (`media.generateVideo`): ask fal.ai, wait for the video, keep it in Files. */
export async function generateVideo(
  viewer: Viewer,
  input: { prompt: string; model: string; aspect: "16:9" | "9:16" | "1:1"; seconds: number; imageFileId?: string | null },
  onProgress: (f: number) => void = () => {},
) {
  const spec = VIDEO_MODELS.find((m) => m.id === input.model) ?? VIDEO_MODELS[0];
  let model = spec.id;
  const body: Record<string, unknown> = { prompt: input.prompt.slice(0, 2000), aspect_ratio: input.aspect, duration: String(input.seconds) };
  if (input.imageFileId && spec.image) {
    const [f] = await db.select({ key: files.storageKey }).from(files).where(and(eq(files.id, input.imageFileId), eq(files.tenantId, viewer.tenantId))).limit(1);
    if (f?.key) {
      body.image_url = await presignDownload(f.key, { expiresIn: 3600 });
      model = spec.image;
    }
  }
  const q = await fetch(`https://queue.fal.run/${model}`, { method: "POST", headers: falHeaders(), body: JSON.stringify(body), signal: AbortSignal.timeout(60_000) });
  const queued = (await q.json().catch(() => ({}))) as FalQueued;
  if (!q.ok || !queued.status_url || !queued.response_url) {
    throw new Error(q.status === 401 || q.status === 403 ? "fal.ai 不认这个密钥" : q.status === 402 ? "fal.ai 余额不足，请先充值" : `fal.ai 没接这个任务：${JSON.stringify(queued.detail ?? queued).slice(0, 200)}`);
  }
  const started = Date.now();
  for (;;) {
    await new Promise((r) => setTimeout(r, 5000));
    const s = (await (await fetch(queued.status_url, { headers: falHeaders() })).json().catch(() => ({}))) as { status?: string };
    const elapsed = Date.now() - started;
    onProgress(Math.min(0.85, elapsed / 240_000));
    if (s.status === "COMPLETED") break;
    if (s.status === "FAILED" || s.status === "ERROR") throw new Error("fal.ai 生成失败，换个描述再试一次");
    if (elapsed > 15 * 60_000) throw new Error("生成超过 15 分钟还没好，已放弃，请再试一次");
  }
  const out = (await (await fetch(queued.response_url, { headers: falHeaders() })).json().catch(() => ({}))) as { video?: { url?: string }; detail?: unknown };
  const url = out.video?.url;
  if (!url) throw new Error(`fal.ai 没有返回视频：${JSON.stringify(out.detail ?? out).slice(0, 160)}`);
  onProgress(0.9);
  const bytes = new Uint8Array(await (await fetch(url, { signal: AbortSignal.timeout(300_000) })).arrayBuffer());
  const made = await importVideoBytes(viewer, {
    bytes,
    name: `AI 生成 · ${input.prompt.replace(/\s+/g, " ").slice(0, 30)}`,
    attribution: `AI 生成（${spec.zh}）`,
    source: input.prompt.slice(0, 500),
    meta: { source: "ai-video", model, prompt: input.prompt.slice(0, 1000), kind: "video", fetchedAt: new Date().toISOString() } as never,
    tags: ["ai-generated"],
  });
  onProgress(1);
  return { fileId: made.id, name: made.name, durationMs: made.durationMs, model };
}
