/**
 * What a server action or a failed call said, in Chinese, for someone using
 * the site in Chinese (QA, 2 Oct: toasts like "Not allowed" and "That script
 * is locked." reached people who never chose English). The toaster runs
 * every notice through this; an English reader sees the original. A line
 * that is already Chinese, or one this does not know, is left as it is.
 */

const EXACT: Record<string, string> = {
  "Not allowed": "没有权限",
  "Not found": "找不到了",
  "Not signed in": "请先登录",
  "Sign in again": "请重新登录",
  "That took too long. Sign in again": "等待太久了，请重新登录",
  "Sign-in is unavailable right now. Try again in a moment": "暂时无法登录，请稍后再试",
  "Your account is not active. Ask an admin": "你的账号还没启用，请联系管理员",
  "Bad request": "请求有误，请刷新后再试",
  "Something went wrong": "出了点问题，请再试一次",
  "No such message": "找不到这条消息",
  "No such button": "这个按钮已经失效了",
  "No such project": "没有这个项目",
  "No such platform": "不支持这个平台",
  "Unknown platform": "不支持这个平台",
  "No such article": "找不到这篇文章",
  "No such publication": "找不到这条发布记录",
  "No such aspect": "不支持这个画幅",
  "No such automation": "没有这个自动任务",
  "No such language": "不支持这种语言",
  "Unknown language": "不支持这种语言",
  "Unknown stage": "没有这个阶段",
  "No such job": "找不到这个任务",
  "Topic not found": "找不到这个选题",
  "That topic does not exist": "找不到这个选题",
  "That script does not exist": "找不到这个脚本",
  "That folder does not exist": "找不到这个文件夹",
  "That file does not exist, or you may not open it": "文件不存在，或者你没有打开的权限",
  "That picture does not exist, or you may not open it": "图片不存在，或者你没有打开的权限",
  "That graphic does not exist": "找不到这个图形",
  "Somebody already answered this": "已经有人处理过了",
  "That script is locked": "脚本已批准锁定，先点「继续编辑」",
  "That script is locked: it was approved. Unlock it on its page before writing a new draft. Nothing was written and no project was created": "脚本已经批准锁定，先在脚本页解锁再写新稿。这次什么都没写，也没有新建项目。",
  "There is nothing to save, or the script is locked": "没有可保存的内容，或者脚本已锁定",
  "There is nothing to save, or the article is published": "没有可保存的内容，或者文章已发布",
  "There is nothing to approve yet, or the script is locked": "还没有可以审批的内容，或者脚本已锁定",
  "There is nothing to approve yet, or the script is already locked": "还没有可以审批的内容，或者脚本已锁定",
  "There is nothing to approve yet, or the article is published": "还没有可以审批的内容，或者文章已发布",
  "That version does not exist, or the script is locked": "这个版本不存在，或者脚本已锁定",
  "That version does not exist, or the article is published": "这个版本不存在，或者文章已发布",
  "The version this names no longer exists": "这个版本已经不存在了",
  "The version this approval names no longer exists": "这次审批对应的版本已经不存在了",
  "This version has changed since approval was requested. Ask for it again": "发起审批之后稿子又改过了，请重新发起审批",
  "The article has changed since it was sent. Ask for it again": "发出之后文章又改过了，请重新发起",
  "That approval is not waiting": "这个审批已经处理过了",
  "Only an owner or admin can approve": "只有负责人或管理员可以审批",
  "Only the person asked, or an admin, can decide this approval": "只有被请求的人或管理员可以处理这个审批",
  "Somebody else was asked to approve this": "这个审批请的是别人",
  "A script cannot be approved by the person who wrote it": "自己写的脚本不能自己审批",
  "An article cannot be approved by the person who wrote it": "自己写的文章不能自己审批",
  "A version cannot be approved by the person who wrote it": "自己写的版本不能自己审批",
  "Choose who should approve it": "请选一位同事来审批",
  "Choose a person in this studio to approve it": "请选一位工作室的同事来审批",
  "Choose at least one channel before asking for approval": "先选至少一个渠道，再发起审批",
  "That article is published. Retract it before editing": "文章已经发布，先撤回再修改",
  "That article is published. Retract it before rewriting": "文章已经发布，先撤回再重写",
  "A script needs a title": "脚本需要一个标题",
  "A project needs a title": "项目需要一个名字",
  "A post needs a title": "发布内容需要一个标题",
  "An article needs a headline to start from": "文章需要先有一个标题",
  "Say what the script is about": "说一下这个脚本讲什么",
  "Say what to change": "说一下要怎么改",
  "Say where it was published": "说一下发布在哪里",
  "Select some text first": "先选中一段文字",
  "Write something first": "先写点内容",
  "A reply cannot be empty": "回复不能是空的",
  "That reply is too long": "回复太长了",
  "That reply has already been sent": "这条回复已经发出去了",
  "That draft has already been sent or withdrawn": "这份草稿已经发出或撤回了",
  "That comment has already been dealt with": "这条批注已经处理过了",
  "There is nothing to send": "没有可以发送的内容",
  "There is nothing to check yet": "还没有可以检查的内容",
  "Nothing selected": "还没有选中任何内容",
  "Nothing to add": "没有可以添加的",
  "Nobody to add": "没有可以添加的人",
  "Nobody here has that name": "工作室里没有这个人",
  "Nobody here has that id": "工作室里没有这个人",
  "That person is not in this studio": "这个人不在工作室里",
  "Pick at least one person in this studio": "至少选一位工作室的同事",
  "Pick who to share with": "选一下要分享给谁",
  "Pick view or edit": "选「可查看」或「可编辑」",
  "Too many at once. Select fewer than 100": "一次选太多了，请少于 100 个",
  "A folder needs a name": "文件夹需要一个名字",
  "A team needs a name": "小组需要一个名字",
  "That name is too long": "名字太长了",
  "That title is too long": "标题太长了",
  "That is longer than a name needs to be": "名字太长了",
  "That is longer than a team name needs to be": "小组名太长了",
  "That channel name is too long": "频道名太长了",
  "That category is too long": "分类名太长了",
  "That brief is longer than a brief": "简介太长了，精简一点",
  "You need a name people can see": "请填一个大家看得到的名字",
  "Please give the name you want to be known by": "请填写你希望大家怎么称呼你",
  "That email and password do not match": "邮箱和密码不匹配",
  "That is not your current password": "当前密码不对",
  "That is not your password": "密码不对",
  "That is the password you already have": "新密码和现在的一样",
  "That password is too long": "密码太长了",
  "A password needs at least 10 characters": "密码至少需要 10 个字符",
  "Use at least 12 characters": "至少需要 12 个字符",
  "Enter the 6-digit code from the app": "请输入验证器里的 6 位数字",
  "That code is not right": "验证码不对",
  "That code is not right. Check the clock on your phone": "验证码不对，请检查手机的时间是否准确",
  "Two-step verification is already on": "两步验证已经开启了",
  "Two-step verification is not on": "两步验证还没有开启",
  "Start again — that setup has expired": "这次设置已过期，请重新开始",
  "That invitation has been used already": "这个邀请已经用过了",
  "That invitation has been used already, or it has expired": "这个邀请已经用过或已过期",
  "The account could not be created. Ask whoever invited you to send a fresh link": "账号没能创建，请让邀请你的人重新发一个链接",
  "no email service configured": "还没有配置邮件服务",
  "Only an owner or an administrator changes the studio's model": "只有负责人或管理员可以修改工作室的模型",
  "Only an owner or an administrator can do that": "只有负责人或管理员可以这样做",
  "Only a file's owner or an admin can change who sees it": "只有文件的主人或管理员可以修改谁能看",
  "Only the person who started it, or an admin, can change who sees it": "只有发起人或管理员可以修改谁能看",
  "Only the person who started it, or an admin, can delete it": "只有发起人或管理员可以删除",
  "Only the project's owner or an admin can change who has access": "只有项目负责人或管理员可以修改权限",
  "Only the project's owner or an admin can delete it": "只有项目负责人或管理员可以删除",
  "Only a full member can connect a channel": "只有正式成员可以连接渠道",
  "You do not hold the Script module": "你还没有脚本模块的权限",
  "You do not have the Script module": "你还没有脚本模块的权限",
  "You do not hold the Video module": "你还没有视频模块的权限",
  "You do not hold the Publish module": "你还没有发布模块的权限",
  "Exporting writes a report into Files, which you do not have": "导出会把报告存进「文件」，你还没有文件模块的权限",
  "This project's video was shared with you to view. Ask its owner for edit access": "这个项目的视频只分享给你查看，需要编辑请找负责人开权限",
  "That is not a time": "时间格式不对",
  "Those are not times": "时间格式不对",
  "That is not a date and time": "日期时间格式不对",
  "A due date looks like 2026-09-30": "截止日期的格式是 2026-09-30",
  "It ends before it starts": "结束时间早于开始时间",
  "That is not a level": "没有这个级别",
  "That is not a model": "没有这个模型",
  "That model is not in the catalogue": "这个模型不在可选列表里",
  "That is not a state of this project": "项目没有这个状态",
  "That is not a transition": "不能这样切换",
  "That is not one of the pictures on offer": "请从给出的图片里选",
  "Choose a voice": "请选一个声音",
  "Pick at least one series": "至少选一条数据",
  "Type a phrase first": "先输入一个关键词",
  "Type a phrase to look for": "输入要找的关键词",
  "A topic needs a phrase to watch": "选题需要一个关注的关键词",
  "That phrase is too long to search": "关键词太长了",
  "That phrase is too long to watch": "关键词太长了",
  "Could not start watching that phrase": "没能开始关注这个关键词",
  "A channel id or handle is needed": "请填写频道 ID 或账号名",
  "A channel id is needed": "请填写频道 ID",
  "That channel is not on this post": "这条发布没有选这个渠道",
  "That one already went out": "这条已经发出去了",
  "That one is already marked as taken down": "这条已经标记为下架了",
  "Fewer than three videos are synced, which is not enough to say anything true about the channel": "同步到的视频少于 3 条，还不足以分析这个账号",
  "Too little has been collected to say anything worth making": "收集到的内容太少，还提不出值得做的选题",
  "No YouTube key is configured on this deployment": "还没有配置 YouTube 接口",
  "No outside-world key is configured on this deployment, so nobody else's channel can be read": "还没有配置外部数据接口，暂时读不了别人的账号",
  "There is no DeepSeek key on this deployment": "还没有配置 DeepSeek 账号",
  "No TikHub key": "还没有配置 TikHub 接口",
  "No transcription key is configured on this deployment": "还没有配置转写服务",
  "No stock library is configured; upload the clips instead": "还没有配置素材库，请上传素材",
  "No stock footage matched this topic; upload the clips instead": "素材库里没有合适的画面，请上传素材",
  "Zernio did not return a consent link": "授权服务没有返回授权链接，请稍后再试",
  "Zernio has no workspace for this key to connect into": "授权服务还没有可连接的工作区",
  "That render has not finished yet": "成片还没渲染完",
  "It is already making this video. Wait for it to finish, or undo afterwards": "这条视频正在制作中，请等它完成，或者完成后再撤销",
  "Put some footage in the bin first: drop a clip on the editor": "先把素材放进素材箱：把视频拖进剪辑页",
  "Put some footage on the timeline first, so there is audio to transcribe": "先把素材放到时间线上，才有声音可以转写",
  "Put something on the timeline first, so there is a length to spread them over": "先往时间线放点内容，才能排布",
  "None of the footage on the timeline has any sound to transcribe": "时间线上的素材都没有声音，无法转写",
  "Nothing on the timeline produced any audio": "时间线上没有任何声音",
  "Nothing was said, or nothing could be made out": "没有听到说话，或者听不清",
  "Every cut's source file is missing": "所有片段的源文件都找不到了",
  "Move the playhead further into the clip before splitting": "先把播放头移到片段中间再分割",
  "Only a finished voice-over has timings to caption from": "配音完成后才能按它的时间出字幕",
  "That is longer than one voice-over should be. Split it": "这段配音太长了，请拆开",
  "That clip came back empty": "这个片段是空的",
  "That clip could not be fetched": "这个片段下载不下来",
  "That clip is not served over https": "这个片段的链接不安全（不是 https）",
  "That clip is too big to bring in": "这个片段太大了，放不进来",
  "That file is not a picture": "这个文件不是图片",
  "That is not a picture": "这不是图片",
  "That link is not a picture": "这个链接不是图片",
  "That picture came back empty": "这张图片是空的",
  "That picture could not be fetched": "这张图片下载不下来",
  "A graphic needs something to say": "图形需要有文字内容",
  "A title card has nothing to split": "标题卡没有可以拆分的内容",
  "Could not put that back": "没能恢复",
  "Could not read the conversation": "读不了这段对话",
  "could not be read": "读不出来",
  "The model returned nothing": "AI 没有返回内容，请再试一次",
  "The model returned nothing to send": "AI 没有返回可以发送的内容，请再试一次",
  "The model did not answer in a shape we could read": "AI 的回答格式不对，请再试一次",
  "The model did not return a script we could read": "AI 没有写出能用的脚本，请再试一次",
  "The model did not return an article we could read": "AI 没有写出能用的文章，请再试一次",
  "The check did not come back in a form we could read": "检查结果读不出来，请再试一次",
  "The answer was interrupted before it finished": "回答到一半中断了，请再试一次",
  "No model produced a plan": "所有模型都没能写出计划，请稍后再试",
  "The upload did not finish": "上传没成功",
  "Failed to fetch": "网络连接中断，请检查网络后再试",
  "Load failed": "网络连接中断，请检查网络后再试",
  "NetworkError when attempting to fetch resource.": "网络连接中断，请检查网络后再试",
};

const KEYS = new Map(Object.entries(EXACT).map(([k, v]) => [norm(k), v]));

function norm(s: string): string {
  return s.trim().replace(/[.。!！]+$/, "").replace(/\s+/g, " ").toLowerCase();
}

/** Starts that still say enough to put into Chinese, with the rest kept. */
const PREFIX: [RegExp, (m: RegExpExecArray) => string][] = [
  [/^GDELT is rate-limiting this address/i, () => "GDELT 暂时限流了，稍后会自动重试"],
  [/^GDELT said (\d+)/i, (m) => `GDELT 暂时出错（${m[1]}），稍后再试`],
  [/^An unexpected response was received from the server/i, () => "服务器刚刚更新过，请刷新页面再试"],
  [/^Failed to find Server Action/i, () => "网站刚刚更新过，请刷新页面再试"],
  [/^(Request|The operation) (timed out|was aborted)/i, () => "等待太久了，请再试一次"],
];

export function zhNotice(text: string): string {
  if (!text || /[一-鿿]/.test(text)) return text;
  const hit = KEYS.get(norm(text));
  if (hit) return hit;
  for (const [re, make] of PREFIX) {
    const m = re.exec(text);
    if (m) return make(m);
  }
  return text;
}
